name:    atman
version: "0.0.0"

dependencies:
- base
- cron
- yesod-core
- yesod-persistent
- protolude
- resourcet
- persistent
- persistent-postgresql
- monad-logger
- monad-control
- mtl
- unix

default-extensions: 
- NoImplicitPrelude
- OverloadedStrings
- DeriveGeneric
- GADTs
- FlexibleContexts
- RankNTypes
- RecordWildCards
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- TypeFamilies

flags:
  production: 
    description: To set production environment
    default: false
    manual: false
# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: flag(production)
    then: 
      cpp-options: -DPRODUCTION
    else:
      cpp-options: -DNOTPRODUCTION
  dependencies:
  - aeson
  - cryptonite
  - fb
  - exceptions
  - HandsomeSoup
  - http-conduit
  - http-client
  - http-client-tls
  - http-types
  - hxt
  - hxt-curl
  - parsec
  - persistent-template
  - regex-compat-tdfa
  - text
  - transformers
  - wai

# Runnable executable for our application
executables:
  atman:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atman
